const data = [
    [
        1,
        44972,
        44958,
        "NC Interne",
        "BARTHET",
        48258,
        5000,
        "Spot à l'envers, Dimitri, M4",
        undefined,
        undefined,
        undefined,
        45002,
        undefined,
        undefined,
        undefined,
        2952
    ],
    [
        2,
        44981,
        44958,
        "NC Client",
        "Monin",
        49394,
        undefined,
        "Nombre de pose en Laize pas bon, Mohamed",
        "3 etiquettes en laize au lieu de 2",
        undefined,
        "OPE",
        45011,
        undefined,
        "Refabrication",
        undefined,
        399.01
    ],
    [
        3,
        44977,
        44958,
        "NC Client",
        undefined,
        4924,
        undefined,
        "Montage + Découpage pas centré",
        "il y'a des crois au centre de certaines étiquettes",
        undefined,
        undefined,
        45007,
        undefined,
        "Avoir de 20%",
        undefined,
        244.47
    ],
    [
        4,
        44975,
        44958,
        "NC Interne",
        "ADS",
        "48811/00",
        200000,
        "Cliché Absents + Manquant / 2 erreurs clichés / 1 Fichiers Manquant",
        undefined,
        undefined,
        undefined,
        45005,
        undefined,
        "Recommande",
        undefined,
        2952
    ],
    [
        5,
        44974,
        44958,
        "NC Client",
        "Michel et augustin",
        "E048986",
        undefined,
        "Pb sens de sortie BAT validé par le client",
        undefined,
        undefined,
        undefined,
        45004,
        undefined,
        "Avoir de 10%",
        undefined,
        317.32
    ],
    [
        6,
        44971,
        44958,
        "NC Client",
        undefined,
        49052,
        1000,
        "Mauvais Sens d'enroulement, David, Grapho",
        undefined,
        undefined,
        "OPE",
        45001,
        undefined,
        "Rebobiner",
        undefined,
        100
    ],
    [
        7,
        44970,
        44958,
        "NC Client",
        "LP2I",
        undefined,
        55000,
        "Livré mal condiotionné",
        undefined,
        undefined,
        undefined,
        45000,
        undefined,
        undefined,
        undefined,
        200
    ],
    [
        8,
        44965,
        44958,
        "NC Client",
        "CROQUET CHAROST",
        undefined,
        24000,
        "Pb d'impression, Modèle Flou, QR code Flou, Décalage d'impression",
        undefined,
        undefined,
        undefined,
        44995,
        undefined,
        undefined,
        undefined,
        undefined
    ],
    [
        9,
        undefined,
        undefined,
        "NC Interne",
        "Monin",
        undefined,
        undefined,
        "Pb étiquettes traçabilité,erreur ref, N Dossier au lieu de Ref Client",
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        100
    ],
    [
        10,
        44960,
        44958,
        "NC Interne",
        "FFDM",
        undefined,
        10000,
        "Pb refente CF2",
        undefined,
        undefined,
        undefined,
        44990,
        undefined,
        undefined,
        undefined,
        69.2
    ],
    [
        11,
        44943,
        44927,
        "NC Client",
        "Monin",
        "45737/738 ET 47739/735",
        77500,
        "Les étiquettes restent sur la glassine, ne se cole pas sur les bouteils",
        undefined,
        undefined,
        undefined,
        44973,
        undefined,
        undefined,
        undefined,
        288.45
    ],
    [
        12,
        44995,
        44986,
        "NC Interne",
        "Bernardy",
        "E049509/12",
        undefined,
        "Plan de travail SCREEN incorrect",
        "Laize papier supérieur à 320mm",
        "prépresse",
        "OPE",
        45025,
        undefined,
        "Sensibilisation PAO",
        undefined,
        250
    ],
    [
        13,
        44995,
        44986,
        "NC Interne",
        "INITIA FOOD",
        "E049028",
        3000,
        "Erreur de vernis",
        "Changement de vernis pour etiquettes presque identique",
        "Machine",
        "OPE",
        45025,
        undefined,
        "Sensibilisation a relir le dossier de fabrication",
        undefined,
        76.97
    ],
    [
        14,
        44995,
        44986,
        "NC Client",
        "Triballat",
        "E048320",
        5000,
        "Pas de vernis, SCREEN",
        "L'encrage de la machine ne permet pas d'adherer avec le repiquage",
        "Machine",
        "ASP",
        45025,
        undefined,
        "Refabrication",
        undefined,
        326.7
    ],
    [
        15,
        44995,
        44986,
        "NC Client",
        "Millet",
        "E049586",
        6000,
        "Matière contre étiquettes modifié",
        undefined,
        "prépresse",
        undefined,
        45025,
        undefined,
        undefined,
        undefined,
        557.36
    ],
    [
        16,
        44995,
        44986,
        "NC Client",
        "DOMAINE DE BEAUREPAIRE",
        "49388 / 49389",
        10000,
        "Erreur sens d'enroulement",
        undefined,
        undefined,
        undefined,
        45025,
        undefined,
        "Le client a rebobiné",
        undefined,
        50
    ],
    [
        17,
        44994,
        44986,
        "NC Client",
        "CROQUET DE CHAROST",
        "E049493",
        500,
        "Trait blanc sur l'étiquette",
        undefined,
        undefined,
        undefined,
        45024,
        undefined,
        "Refabrication",
        undefined,
        528.56
    ],
    [
        18,
        44991,
        44986,
        "NC Client",
        "Triballat",
        47679,
        55000,
        "Glassine fragilisé, David sur la grapho",
        undefined,
        undefined,
        undefined,
        45021,
        undefined,
        undefined,
        undefined,
        98.4
    ],
    [
        19,
        44991,
        44986,
        "NC Client",
        "Triballat",
        46211,
        7000,
        "Manque des étiquettes sur le rouleau",
        undefined,
        undefined,
        undefined,
        45021,
        undefined,
        undefined,
        undefined,
        110.46
    ],
    [
        20,
        44991,
        44986,
        "NC Client",
        "Triballat",
        47703,
        14000,
        "Précense de double ou manque d'étiquettes",
        undefined,
        undefined,
        undefined,
        45021,
        undefined,
        undefined,
        undefined,
        174.6
    ],
    [
        21,
        44991,
        44986,
        "NC Client",
        "Triballat",
        46781,
        7000,
        "Manque des étiquettes sur le rouleau",
        undefined,
        undefined,
        undefined,
        45021,
        undefined,
        undefined,
        undefined,
        110.46
    ], 
    // 2022 Start
        [
            1,
            44574,
            44574,
            "NC Interne",
            undefined,
            undefined,
            undefined,
            "Erreur d'envoi à WINK commande non annulé par l'opératrice (PAO)",
            "Erreur d'envoi\nInattention PAO\nPas identifié",
            "prépresse",
            "OPE",
            44604,
            "N. LAVALETTE",
            "Pas d'action particulière",
            44664,
            160.04000000000002,
            "NOK"
        ],
        [
            2,
            44596,
            44596,
            "NC Interne",
            undefined,
            3371,
            undefined,
            "erreur de couleur sur l'étiquette (couleur spécial)",
            "Pas d'info entre opérateur PAO",
            "prépresse",
            "OPE",
            44626,
            "N. LAVALETTE",
            "Chercher l'erreur/ nouvelle teinte OK\nretirage",
            44596,
            597.56,
            "OK"
        ],
        [
            3,
            44599,
            44599,
            "NC Interne",
            undefined,
            1893,
            undefined,
            "Manque un cliché de vernis",
            "PAO Pas commandé",
            "prépresse",
            "OPE",
            44629,
            "N. LAVALETTE",
            "Essai avec une autre façon\ncommande du cliché ",
            44599,
            350,
            "OK"
        ],
        [
            4,
            44599,
            44599,
            "NC Interne",
            undefined,
            4332,
            undefined,
            "6 dossiers espaces en laize sur 5 dossiers 3 mm\nsur 1 dossier 4 mm\nmagnésium et cliché ont perte de temps",
            "PAO pas fait attention et rationalisé les dessins\nCommercial aurait du optimisé aussi.\n",
            "prépresse",
            "OPE",
            44629,
            "N. LAVALETTE",
            "Enlevé les repères sur le magnésium pour faire les étiquettes espace laize 3 mm",
            44600,
            285,
            "OK"
        ],
        [
            5,
            44594,
            44594,
            "NC Client",
            "Triballat",
            "E044455",
            undefined,
            "Constaté par le client, erreur sur étiquetage d'une référence",
            "Base reprise mais pas la bonne référence",
            undefined,
            "DOC",
            44624,
            undefined,
            undefined,
            44664,
            50,
            "OK"
        ],
        [
            6,
            44594,
            44594,
            "NC Client",
            "Triballat",
            "E044455",
            undefined,
            "Erreur étiquetage sur photo, il s'agit de 5095 à l'intérieur et identifié 5090\nBL manquant de 5094 et 5228",
            undefined,
            undefined,
            "DOC",
            44624,
            undefined,
            "Sensibilisation PAO",
            44664,
            50,
            "OK"
        ],
        [
            7,
            44613,
            44613,
            "NC Client",
            "Girault&Fils",
            45545,
            undefined,
            "Erreur PAO\nDouble : Magnésium faux\nrepère des étiquettes",
            "Erreur PAO sur plan de travail\nErreur PAO sur fichier dorure",
            "prépresse",
            "OPE",
            44643,
            "F.MUSE",
            "refabrication\n+ commande magnésium",
            44613,
            1340.82,
            "OK"
        ],
        [
            8,
            44609,
            44609,
            "NC Client",
            "Monin",
            "E045274\nE045273",
            "20000\n50000",
            "Problème conditionnement des rouleaux",
            "Problème machine ==> Enroulement manuel\nTravail le samedi sans Responsable qui libère le produit",
            "Machine",
            "OPE",
            44639,
            "F.MUSE",
            "Photo à chaque bobine\nConcertation avant enroulement\nValidation pour libération produit",
            "08/03/222",
            625,
            "OK"
        ],
        [
            9,
            44565,
            44565,
            "NC Client",
            "Monin",
            undefined,
            undefined,
            "Les rouleaux ne possèdent pas d'identification\nLes rouleaux cassent en passage en production\nLa hauteur de la bande de l'étiquette varie",
            undefined,
            "Machine",
            "MAC",
            44595,
            undefined,
            "2 étiquettes sont mis en place (soldé)",
            44664,
            50,
            "OK"
        ],
        [
            10,
            44616,
            44616,
            "NC Client",
            "ADHEX",
            "E045119",
            20000,
            "Problème Réception :Palette abimée Transport DB SCHENKER",
            undefined,
            "Logistique",
            "OPE",
            44646,
            undefined,
            "marchandises non abîmées",
            44664,
            50,
            "ok"
        ],
        [
            11,
            44641,
            44641,
            "NC Interne",
            "Auchère",
            45976,
            70000,
            "Erreur de cliché de l'opérateur grafo",
            "BAT non vérifié après collage du module",
            "prépresse",
            "OPE",
            44671,
            "F.MUSE",
            "refaire\nsolution informatique",
            44641,
            3140.5,
            "OK"
        ],
        [
            12,
            44664,
            44664,
            "Litige fournisseur",
            "MANTER",
            undefined,
            "498,75m²",
            "Bobine inexploitable",
            undefined,
            "Logistique",
            undefined,
            44694,
            "N. LAVALETTE",
            "avoir reçu",
            44693,
            undefined,
            "ok"
        ],
        [
            13,
            44678,
            44678,
            "NC Client",
            "Monin",
            "E045735",
            10000,
            "Présence des tâches roses sur des étiquettes",
            "Présence de poussières sur les clichés\nLa caméra n'est pas dimensionné pour un contrôle millimétrique à ce niveau\nle barboteur a du mal a tourné correctement de temps en temps",
            "Machine",
            "ASP",
            44708,
            "N. LAVALETTE",
            "• Les prochaines fabrications seront sur la machine numérique qui est en cours d'installation dans un local isolé de la poussière et climatisé, (après l'accord du client)\n• étude de requalification de la caméra (couleur et de détection dimensionnelle\n• sensibilisation de nos fournisseurs\n• Maintenance et changement de roulement des barboteurs \n",
            44754,
            150.8,
            "ok"
        ],
        [
            14,
            44679,
            44679,
            "NC Client",
            "Monin",
            "E045737",
            2000,
            "Manque une couleur sur les étiquettes",
            "Inattention de l'opérateur qui n'a pas pu contrôlé les bacs d'approvisionnement des encres.\nCamera de contrôle qui contrôle la forme mais elle ne contrôle pas la couleur",
            "Machine",
            "ASP",
            44709,
            "N. LAVALETTE",
            "Sensibilisation des opérateurs\nLes prochaines fabrications seront sur la machine numérique qui est en cours d'installation dans un local isolé de la poussière et climatisé, (après l'accord du client)\nétude de requalification de la caméra (couleur et de détection dimensionnelle",
            44754,
            70.16,
            "ok"
        ],
        [
            15,
            44685,
            44685,
            "NC Client",
            "Monin",
            "E045739",
            10000,
            "Apparition des tâches blanches sur l'étiquette",
            undefined,
            "Machine",
            "ASP",
            44715,
            "C.LAUVERGEAT",
            "Impression sur la numérique pour ce client",
            44754,
            93.68,
            "ok"
        ],
        [
            16,
            44692,
            44692,
            "NC Client",
            "SCEV DOMAINE DES BALLANDORS",
            "E045691\nE044857",
            "20000\n30000",
            "Découpe trop prononcée, la bande casse sur la machine de pose",
            "Trop de pression sur la découpe\nManque d'attetion des opérateurs",
            "Machine",
            "ASP",
            44722,
            undefined,
            "Vérifcation des réglages et refabrication",
            44754,
            50,
            undefined
        ],
        [
            17,
            44691,
            44691,
            "NC Client",
            "Villalin",
            "E045783",
            1500,
            "Erreur adresse sur l'étiquette. BAT validé par le client mais le cliché n'a pas été commandé. Tirage avec l'ancien modèle",
            "Oubli de la PAO\nDes modifications et changement d'adresse rarement",
            "prépresse",
            "OPE",
            44721,
            "C.LAUVERGEAT",
            "Modification de l'étiquette\nNouveau BAT\nNouveau Cliché",
            44691,
            477,
            "ok"
        ],
        [
            18,
            44684,
            44684,
            "NC Client",
            "ISOTHERM",
            "E043490",
            184000,
            "Epaisseur de glassine trop importante qui implique un déchirement lors de décollage de l'étiquette.",
            "Choix de la 1ère matière en stock disponible dû à l'urgence de la commande.",
            "Commercial",
            "CHO",
            44714,
            "N. LAVALETTE",
            "Vérification de la matière 1ère\nValidation de la matière par le client en cas d'urgence",
            "12/07/220",
            2072.2,
            "ok"
        ],
        [
            19,
            44706,
            44706,
            "NC Client",
            "LP2I",
            "E045467",
            2500,
            "Les livrets ne s'ouvrent pas",
            "Mauvais séchage du verni\nContrôle irrégulier",
            "Machine",
            "OPE",
            44736,
            "N. LAVALETTE",
            "Refabrication\nAccentuer les contrôles",
            44712,
            278.4,
            "OK"
        ],
        [
            20,
            44708,
            44708,
            "NC Client",
            "Rians",
            "E046481",
            30000,
            "Les rouleaux cassent en cours d'utilisation",
            "Trop de pression sur la glassine\nLes rouleaux ne suivent pas le process habituel de fabrication",
            "Machine",
            "OPE",
            44738,
            "F.MUSE",
            "Reprendre le mode opératoire sur la machine\nDétecter les NC Interne",
            44824,
            50,
            "OK"
        ],
        [
            21,
            44735,
            44735,
            "NC Client",
            "ISOTHERM",
            "E043490",
            184000,
            "Déchirement de la glassine + spot noir au verso non demandé. ",
            "Epaisseur plus importante\nValidation de la MP en urgence",
            "Logistique",
            "ASP",
            44765,
            "N. LAVALETTE",
            "Revoir et valider la MP avec le client avant production",
            44824,
            2434.64,
            "OK"
        ],
        [
            22,
            44747,
            44747,
            "NC Client",
            "LEBRUN",
            "E046915/918/917",
            3000,
            "pas la bonne référence",
            "Erreur de fichier de la part du commercial",
            "Commercial",
            "ASP",
            44777,
            "C.LAUVERGEAT",
            "récupération et mise en stock des étiquettes\nRefabrication et avoir réalisé",
            44754,
            50,
            "OK"
        ],
        [
            23,
            44725,
            44725,
            "NC Client",
            "FISH BRENNE",
            "E044481",
            3000,
            "Problème dorure à chaud :\nManque dorure\nCasse dû à la dorure",
            "Manque Dorure dû un manque de contrôle visuel et la gestion de pression\nla casse d'étiquette  est dû la gestion de la pression (dizaine d'étiquettes)",
            "Machine",
            "OPE",
            44755,
            "F.MUSE",
            "Gestion de la pression à étudier avec le constructeur de la machine",
            44718,
            239.48,
            "OK"
        ],
        [
            24,
            44725,
            44725,
            "NC Interne",
            "MABILLOT",
            "E047459",
            2000,
            "Texte manquant, impression quadri OR, erreur PAO sur l'intitulé, KONICA n'imrime pas",
            "Problème machine",
            "prépresse",
            "OPE",
            44755,
            "C.LAUVERGEAT",
            "rebrication ",
            undefined,
            187.92,
            undefined
        ],
        [
            25,
            44725,
            44725,
            "NC Interne",
            "MABILLOT",
            "E047456",
            0,
            "Aperçu à l'écran Konica . Il manque l'impression OR. Erreur PAO",
            undefined,
            undefined,
            undefined,
            44755,
            undefined,
            undefined,
            undefined,
            110,
            undefined
        ],
        [
            26,
            44819,
            44819,
            "NC Client",
            "DEMOISELLES TATIN",
            "E046012",
            undefined,
            "Impression décalée",
            "Commencer le rouleau avec étiquette de calage",
            "Machine",
            "OPE",
            44849,
            "F.MUSE",
            undefined,
            undefined,
            50,
            undefined
        ],
        [
            27,
            44819,
            44819,
            "NC Client",
            "DEMOISELLES TATIN",
            "E046012",
            undefined,
            "Découpe trop prononcée",
            "Point de colle sur le cylindre de pression",
            "Machine",
            "OPE",
            44849,
            "F.MUSE",
            undefined,
            undefined,
            50,
            undefined
        ],
        [
            "28 a",
            44820,
            44820,
            "NC Client",
            "Rians",
            "E04538700",
            undefined,
            "En fin de rouleau, il y a plusieurs étiquettes qui sont décalées sur la glassine générant des arrêts machines. De plus, nous ne pouvons finir les rouleaux complétement (reste plusieurs centaines d'étiquettes).",
            undefined,
            undefined,
            undefined,
            44850,
            undefined,
            undefined,
            undefined,
            50,
            undefined
        ],
        [
            28,
            44848,
            44848,
            "Litige fournisseur",
            "RAFLATAC",
            undefined,
            undefined,
            "Bobine abîmée/voir BL et photos sur la FNC papier",
            "La bobine a été endommagée suite aux erreurs dans le procès d’emballage. ",
            "Logistique",
            "CHO",
            44878,
            "N. LAVALETTE",
            "Réponse fournisseur",
            44853,
            undefined,
            "OK"
        ],
        [
            29,
            44853,
            44853,
            "Litige fournisseur",
            "RAFLATAC",
            undefined,
            undefined,
            undefined,
            "Endommagée par le transporteur",
            "Logistique",
            "CHO",
            44883,
            "N. LAVALETTE",
            "Réponse fournisseur",
            44855,
            undefined,
            "OK"
        ],
        [
            30,
            44869,
            44869,
            "NC Client",
            "LP2I",
            "E048049",
            5000,
            "Erreur d'impression en 100ml au lieu de 250ml",
            "Erreur prépresse",
            "prépresse",
            "OPE",
            44899,
            "N. LAVALETTE",
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            31,
            44837,
            44837,
            "NC Client",
            "LP2I",
            "E047926\nE047825",
            "2000\n2000",
            "Pantone 7664C non-conforme\nPantone 7665C non-conforme + pb de cadrage sur le recto+pb d'impression (flou et non lisible en vitrophanie)",
            undefined,
            undefined,
            undefined,
            44867,
            "N. LAVALETTE",
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            32,
            undefined,
            undefined,
            "NC Client",
            "Rians",
            undefined,
            undefined,
            "Erreur de cliché thermisé au lieu de cru",
            "Erreur de l'opérateur lors du choix des clichés",
            "prépresse",
            "OPE",
            undefined,
            "N. LAVALETTE",
            "Tri séparé des clichés, les clichés pour thermisé seront mis à part car plus utilisés pour le moment\nRelecture de l'oprateur machine le plus possible",
            44855,
            undefined,
            undefined
        ],
        [
            33,
            undefined,
            undefined,
            "NC Client",
            "Rians",
            undefined,
            undefined,
            "Problème d'étiquettes",
            "Mauvais contrôle de la machine au niveau des lames de refente, lors de décélération de la machine, les bandes devenant plus molles se décalents",
            "Machine",
            "ASP",
            undefined,
            "F.MUSE",
            "Contrôle visuel en production (le moins évident du fait de la vitesse)\nContrôle des tensions\nContrôle visuel de la bobine finie avant mise en carton",
            44855,
            undefined,
            undefined
        ],
        [
            34,
            undefined,
            undefined,
            "NC Client",
            "Rians",
            undefined,
            undefined,
            "Manque d'étiquette",
            "Mauvais réglage de la caméra ou non utilisée, nous avons eu une intérimaire qui probablement ne s'est pas servi à 100% correctement de la caméra, l'opératrice est revenue de son AT",
            "Machine",
            "OPE",
            undefined,
            "F.MUSE",
            "Test caméra, \nRappel de l'importance de la mise en place du système contrôle caméra\nUn document existe déjà pour la validation du bon fonctionnement du système (début, en cours et fin)",
            44855,
            undefined,
            undefined
        ],
        [
            35,
            undefined,
            undefined,
            "NC Client",
            "Rians",
            undefined,
            undefined,
            "Etiquettes bague se reportent sur d'autres étiquettes",
            "Problème 1er la matière, qui ne réagit pas de la même façon une fois sur l'autre, possibilité de période de l'année posant plus de problèmes (Chaleur)",
            "Machine",
            "MAC",
            undefined,
            "F.MUSE",
            "Commande d'une nouvelle plaque de découpe, en plus de l'inclinaisonspécifique des filets, un nouveau revêtement colle très forte et qui flue a été commandé\nContrôle visuel quand cela est possible sur le dernier rouleau avant bobinage, compliqué, l'opératrice ne peut avoir l'oeil à 100% sur ce rouleau, la caméra d'inspection étant avant\nTension de la bobine étant au plus bas",
            44855,
            undefined,
            undefined
        ],
        [
            36,
            undefined,
            undefined,
            "NC Client",
            "Rians",
            undefined,
            undefined,
            "Talc",
            "Pour éviter que les étiquettes collent au dernier rouleau avant bobinage, nous talquons ce dernier. Trop de Talc doit être déposé",
            "Machine",
            "MAC",
            undefined,
            "F.MUSE",
            "Tempérer la quantité de talc, supprimer le surplus",
            44855,
            undefined,
            undefined
        ],
        [
            37,
            44895,
            44895,
            "NC Interne",
            "LP2I",
            undefined,
            2000,
            "Prob d'impression + modèles manquants",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            "Refabriquation",
            undefined,
            880,
            undefined
        ],
        [
            38,
            44893,
            44893,
            "NC Interne",
            undefined,
            "E048223",
            undefined,
            "Tirage …?",
            "pas vu",
            undefined,
            undefined,
            undefined,
            undefined,
            "Refabriquation",
            undefined,
            948.96,
            undefined
        ],
        [
            39,
            44893,
            44893,
            "NC Interne",
            "LP2I",
            "48281-282-283",
            1500,
            "Erreur refaise M4, ventralisation colle, Didier M4",
            "pas vu le bout de la machine",
            undefined,
            undefined,
            undefined,
            undefined,
            "Refabriquation",
            undefined,
            722.5,
            undefined
        ],
        [
            40,
            44890,
            44890,
            "NC Interne",
            undefined,
            48437,
            25000,
            "Panne machine, perte de tension",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            "Refabrication",
            undefined,
            770.75,
            undefined
        ],
        [
            41,
            44894,
            44894,
            "NC Client",
            "Comatelec",
            "E047950",
            500,
            "Problème epaisseur, sous-traitant Sonidess refabrique les étiquettes",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            42,
            44879,
            44879,
            "NC Client",
            "MABAMURE",
            "E047888",
            20000,
            "Fabriqué avec coins coupés, veillit alors que demandé sans coins et sans œillet ",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            43,
            44872,
            44872,
            "NC Client",
            "CROQUET CHAROST",
            undefined,
            6000,
            "Problème d'impression sur a SCREEN",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            "Fabrication de 2 séries d'étiquettes offertes",
            undefined,
            undefined,
            undefined
        ],
        [
            44,
            44861,
            44861,
            "NC Client",
            "MONIN",
            47308,
            3078,
            "Problème de découpe trop pononcé, impossible de les poser avec leur machine",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            45,
            44861,
            44861,
            "NC Client",
            "MONIN",
            46860,
            139500,
            "Pb de découpe, impossible de poser les étiquettes avec leur machines",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            46,
            44861,
            44861,
            "NC Client",
            "MONIN",
            47082,
            5000,
            "Pb de découpe, impossible de poser les étiquettes avec leur machines",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            47,
            44841,
            44841,
            "NC Client",
            "FISH BRENNE",
            "E043550",
            1400,
            "Problème dorure OR",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
        [
            48,
            44841,
            44841,
            "NC Client",
            "ATE",
            "E047571",
            5000,
            "Sous-traitance: Guillaud / mauvais conditionnement paquet de 100 au lieu de 50",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
        ],
    
    // 2021 Start
        [
            1,
            44306,
            44306,
            "NC Interne",
            "GNIS",
            "E041917",
            58000,
            "Erreur de numérotation à la PAO",
            "Erreur sens de numérotation",
            "prépresse",
            "DIM",
            44336,
            "E.BENOIT",
            "Erreur détecté encours de production\nnouvelle numérotation",
            44306,
            430,
            "OUI"
        ],
        [
            2,
            44315,
            44315,
            "NC Interne",
            "LP2I",
            42464,
            0,
            "Mauvais montage à la Pao",
            undefined,
            "prépresse",
            "OPE",
            44345,
            "E.BENOIT",
            "Découpe du cliché par le tirage",
            44306,
            250,
            "OUI",
            "Commercial",
            "NC Interne",
            "DIM"
        ],
        [
            3,
            44321,
            44321,
            "NC Client",
            "Michelin",
            "E039005",
            50000,
            "Problème espace étiquette laize trop grande",
            "problème de recoupe",
            "Machine",
            "OPE",
            44351,
            "C.LAUVERGEAT",
            "Recouper plus court\nRepasse les rouleaux sur une machine pour diminuer les rives\nRefaire avec des espaces plus court comme habituellement réalisé",
            44321,
            530,
            "OUI",
            "prépresse",
            "NC Fournisseur",
            "ASP"
        ],
        [
            4,
            44334,
            44334,
            "NC Client",
            "BIGONNEAU EARL",
            "E041806",
            5400,
            "Le code Barre ne correspond pas aux chiffres",
            "Les barres et les chiffres ne correspondent pas\nils ne sont pas fusionnés - un copié/collé séparément",
            "prépresse",
            "OPE",
            44364,
            "E.BENOIT",
            "Refabriquer\nVérifier les codes /les chiffres",
            44324,
            1154,
            "OUI",
            "Machine",
            "NC Client",
            "DOC"
        ],
        [
            5,
            44259,
            44259,
            "NC Client",
            "TRIBALLAT",
            "E041703",
            11000,
            "Manque étiquette sur bobine : pb de déchirement",
            "Conditionnement/ vérification des lames de rasoir/ camera",
            "Machine",
            "OPE",
            44289,
            "N.LAVALETTE",
            "Suivi de toutes les consignes",
            44385,
            220.74,
            "OUI",
            "Logistique",
            "Sous traitance",
            "MAC"
        ],
        [
            6,
            44335,
            44335,
            "NC Fournisseur",
            "MANDEURE",
            undefined,
            "2 BOBINES",
            "Arrachement sur 2 bobines constaté à la réception",
            "pas de retour fournisseur sur l'analyse",
            "Logistique",
            "ASP",
            44365,
            "L.LECROCQ",
            "Avoir reçu",
            44365,
            50,
            "OUI",
            "OUT"
        ],
        [
            7,
            44336,
            44336,
            "NC Client",
            "TJP",
            "E042685",
            24000,
            "Le client a détecté le problème d'impression. Manque le logo eurofeuille sur toutes les cartes étiquettes",
            "Problème de couleur (quadri)\nLe logo n'est pas reconnu informatiquement",
            "prépresse",
            "OPE",
            44366,
            "C.LAUVERGEAT",
            "vérification du texte au lieu du logo",
            44336,
            812.96,
            "OUI",
            "CHO"
        ],
        [
            8,
            44341,
            44341,
            "NC Client",
            "BAHIER",
            undefined,
            undefined,
            "étiquette 'rillettes du Mans' non conforme, avec le gris du pantone (P432C) non respecté, livraison du 14/05/2021",
            "la grille n'a pas été vérifié à la fabrication",
            "prépresse",
            "ASP",
            44371,
            "N.LAVALETTE",
            "Plus  auto-contrôle",
            44341,
            250,
            "OUI",
            "OPE"
        ],
        [
            9,
            44335,
            44335,
            "NC Fournisseur",
            "MANTER",
            undefined,
            4130,
            "Manque BL et manque matière (8000ML commandé et 3870ML reçu)",
            "erreur de saisi",
            "Logistique",
            "MAT",
            44365,
            "N.LAVALETTE",
            "le fournisseur nous a renvoyé le nouveau BL \nil nous a envoyé aussi la suite des commande",
            44355,
            50,
            "OUI",
            "MAT"
        ],
        [
            10,
            44319,
            44319,
            "NC Fournisseur",
            "UPM",
            "BL ° SFR-3614799-1",
            undefined,
            "1 Bobine abimée sur palette et film intact, non visible avant chargement ",
            "pas de retour fournisseur sur l'analyse",
            "Logistique",
            "CHO",
            44349,
            "N.LAVALETTE",
            "Avoir reçu",
            44350,
            50,
            "OUI"
        ],
        [
            11,
            44357,
            44357,
            "NC Client",
            "LP2I",
            undefined,
            2,
            "2 cartons abimés (1 rouleau) reçu par le client",
            "analyse du transporteur : pas de position spécifique définie dans la remorque de traction puisqu’il s’agissait d’effectuer cette prestation dans des conditions normales en messagerie",
            "Logistique",
            "ASP",
            44387,
            "N.LAVALETTE",
            "le transporteur ne facturera pas le transport",
            44363,
            50,
            "OUI"
        ],
        [
            12,
            44358,
            44358,
            "NC Client",
            "la banque de France et ILSA",
            "E042561 (BF)\nE042754 (ILSA)",
            "60Rlx\n200000",
            "Inversion des étiquettes palettes donc erreur de destination",
            "erreur d'étiquetage dû à la présence de plusieurs palettes",
            "Logistique",
            "OPE",
            44388,
            "L.BORDIER",
            "Plus d'organisation à l'expédition",
            44358,
            525,
            "OUI"
        ],
        [
            13,
            44354,
            44354,
            "NC Fournisseur",
            "Color Print",
            "E042816/00",
            1,
            "Découpe non conforme à la commande",
            undefined,
            "Logistique",
            "DIM",
            44384,
            "E.BENOIT",
            "La découpe refaite au bon format par le fournisseur gracieusement",
            44369,
            50,
            "OUI"
        ],
        [
            14,
            44369,
            44369,
            "NC Interne",
            "LA BOVIDA",
            "E043014/00",
            750,
            "Mauvais repérage découpe sur Impression (espace en laize incorrect-erreur sur fiche technique)\ndécoupe commandée avec cette erreur\nabsence du nom sur la fiche technique",
            "Erreur sur fiche technique",
            "Commercial",
            "OPE",
            44399,
            "C.LAUVERGEAT",
            "Recommander des plaques correct\nModification de la fiche technique",
            44369,
            170,
            "OUI"
        ],
        [
            15,
            44382,
            44382,
            "NC Interne",
            "TRIBALLAT",
            "EN 043185",
            300000,
            "Filet de découpe laissé sur cliché limite de texte",
            "BAT du client validé\nPas poser la question \nfaisant parti du décor\nPas consultation client\nProd lancée la fab comme BAT",
            "prépresse",
            "ASP",
            44412,
            "N.LAVALETTE",
            "Se poser la question et appeler le client\nVérifier limite de texte à chaque fois\nMettre en pointillé la limite du texte",
            44383,
            1058,
            "OUI"
        ],
        [
            16,
            44384,
            44384,
            "NC Interne",
            "BIGONNEAU EARL",
            "E043202\nE043203",
            19485,
            "Mauvais fichier : pas tenu compte des informations sur la fiche technique",
            "Inattention\npas de liaison avec la fiche technique\nPas de comparaison avec la dernière impression",
            "prépresse",
            "ASP",
            44414,
            "N.LAVALETTE",
            "Mise à jour de la fiche technique\nfichier Konica : inscription du %\nAlerte Qualité",
            44385,
            576.09,
            "OUI"
        ],
        [
            17,
            44390,
            44390,
            "NC Client",
            "FFDM",
            "E043188\nE043195",
            3000,
            "Problème impression, erreur produite à la Pao. Le client a validé le BAT avec l'erreur",
            "Même procédure mais ce modèle n'était pas au bon format (problème informatique)",
            "prépresse",
            "ASP",
            44420,
            "C.LAUVERGEAT",
            "Plus d'attention, contrôle",
            44390,
            250,
            "OUI"
        ],
        [
            18,
            44392,
            44392,
            "NC Client",
            "FFDM",
            "E043188\nE043195",
            "3000\n1000",
            "Problème de découpe/ de calage des étiquettes",
            "Petir format est donc le papier bouge",
            "Machine",
            "ASP",
            44422,
            "C.LAUVERGEAT",
            "recherche de plus de réglage pour mieux serrer",
            44404,
            150,
            "OUI"
        ],
        [
            19,
            44393,
            44393,
            "NC Interne",
            "Domaines de Bruniers",
            "440/6",
            undefined,
            "Manque de texte - Pao\nImpression numérique",
            "Manque de texte PAO partie texte sans couleurs\nVérification Couleur PAO",
            "prépresse",
            "ASP",
            44423,
            "N.LAVALETTE",
            "Test reprise film transfert thermique",
            44393,
            350,
            "OUI"
        ],
        [
            20,
            44393,
            44393,
            "NC Interne",
            "PIF",
            "43268\n43269",
            undefined,
            "Erreur Matière",
            "FT mélangé\nPas de vérifié matière",
            "Logistique",
            "ASP",
            44423,
            "N.LAVALETTE",
            "Vérifier la matière à chaque fois",
            44393,
            778,
            "OUI"
        ],
        [
            21,
            44398,
            44398,
            "NC Client",
            "BAHIER",
            "E042833",
            undefined,
            "Erreur Modèle , imprimé AD32 au lieu de AD5",
            "décision d'opérateur de se débarrasser du cliché sans concertation",
            "Machine",
            "OPE",
            44428,
            "C.LAUVERGEAT",
            "Demande de vérification par l’opérateur avant exécution ",
            44398,
            300,
            "OUI"
        ],
        [
            22,
            44399,
            44399,
            "NC Interne",
            "Coteaux de haute brune",
            43168,
            5000,
            "Format découpe",
            "Erreur PAO",
            "prépresse",
            "OPE",
            44429,
            "David",
            "Refabriquer",
            44399,
            334.15,
            "OUI"
        ],
        [
            23,
            44404,
            44404,
            "NC Client",
            "LP2i",
            43435,
            500,
            "Manque les références dans les mandrins",
            "Erreur opérateur",
            "Machine",
            "OPE",
            44434,
            "C.LAUVERGEAT",
            "sensibilisation",
            44404,
            50,
            "OUI"
        ],
        [
            24,
            44404,
            44404,
            "NC Client",
            "PILLIVUYT",
            43271,
            140000,
            "MANQUE 6000 étiquettes à la fabrication",
            "erreur de production",
            "Machine",
            "OPE",
            44434,
            "C.LAUVERGEAT",
            "Refabrication ",
            44404,
            300,
            "OUI"
        ],
        [
            25,
            44410,
            44410,
            "NC Interne",
            "Tante agathe",
            43540,
            undefined,
            "Couleur client validée sur autre module non prise en compte par le fichier AD19",
            "PAO pas repris charte et validée",
            "prépresse",
            "OPE",
            44440,
            "N.LAVALETTE",
            "Demande de vérifier et faire la modification\nChangement de fichier avec la bonne couleur",
            44410,
            150,
            "OUI"
        ],
        [
            26,
            44407,
            44407,
            "NC Fournisseur",
            "MANTER",
            undefined,
            "2 BOBINES",
            "Reçu 2 bobines abimées.",
            undefined,
            "Logistique",
            "ASP",
            44437,
            "N.LAVALETTE",
            "avoir reçu",
            43813,
            50,
            "OUI"
        ],
        [
            27,
            44438,
            44438,
            "NC Client",
            "Monin",
            "E043559\nE043560",
            30000,
            "Bobines déformées et non utilisables",
            "Mauvais réglages en machine\nLe tensiomètre mis au max malencontreusement\n",
            "Machine",
            "ASP",
            44468,
            "C.LAUVERGEAT",
            "Reprise\nSensibilisation du personnel\nAlerte Qualité",
            44439,
            250,
            "OUI"
        ],
        [
            28,
            44441,
            44441,
            "NC Interne",
            "Fish Brenne",
            43738,
            6000,
            "Filet de découpe avec pantone au lieu du mot découpe. Impression Numérique filet de découpe imprimé (PAO)",
            "Pass vérification de la couleur de la découpe\nManque de contrôle\nPas respecté la procédure (couleur = impr)",
            "prépresse",
            "OPE",
            44471,
            "N.LAVALETTE",
            "sensibilisation et rappel des techniques au PAO",
            44459,
            440,
            "OUI"
        ],
        [
            29,
            44445,
            44445,
            "NC Client",
            "Renauldon",
            "3 dossiers",
            undefined,
            "Erreur à la cotation malgré la photo du sens de sorti\nErreur non detecté à la PAO. Format impossible avec le sens de sortie",
            "Commercial : manque de lecture des documents du client\nPAO : fait le travail sans regarder la faisabilité",
            "prépresse",
            "OPE",
            44452,
            "N.LAVALETTE",
            "Refabrication et découpe\nInvestissement sur un logiciel auto-contrôle",
            44452,
            950,
            "OUI"
        ],
        [
            30,
            44454,
            44454,
            "NC Client",
            "TJP",
            "E043554",
            6000,
            "Le client a détecté le problème d'impression. Manque le logo eurofeuille sur toutes les cartes étiquettes",
            "Problème de couleur (quadri)\nLe logo n'est pas reconnu informatiquement",
            "prépresse",
            "OPE",
            44484,
            "C.LAUVERGEAT",
            "vérification du texte au lieu du logo",
            44454,
            235,
            "OUI"
        ],
        [
            31,
            44463,
            44463,
            "NC Fournisseur",
            "MANTER",
            undefined,
            "112M",
            "Bobine abîmée",
            "lors du transport",
            "Logistique",
            "ASP",
            44493,
            "L.LECROCQ",
            "Avoir reçu / Aviser le transporteur",
            44469,
            50,
            "non"
        ],
        [
            32,
            44439,
            44439,
            "NC Client",
            "Monin",
            138831,
            "rouleau",
            "Les contre-étiquettes ne se posent pas correctement sur les bidons.\nUn pli se forme sur toute la hauteur de l’étiquette au début de la dépose.\nIl a été constaté que les étiquettes accrochent sur le balai de lissage au moment de leurs sorties pour la dépose sur le bidon\n",
            "Commande de matière PP clear idem PP Blanche pour test\nMatière fourni testé OK sur format +petit\n",
            "Machine",
            "MAC",
            44469,
            "C.LAUVERGEAT",
            "\nMachine de pose suffisante pour la tension?? (vu avec Mr L.PELLERIN à voir avec Mr Therre M.)\n",
            undefined,
            50,
            "OUI"
        ],
        [
            33,
            44474,
            44474,
            "NC Fournisseur",
            "RAFLATAC",
            undefined,
            32.16,
            "Bobine abîmée",
            "lors du transport",
            "Logistique",
            "ASP",
            44504,
            "L.LECROCQ",
            "Avoir reçu / Aviser le transporteur",
            44476,
            50,
            "OUI"
        ],
        [
            34,
            44496,
            44496,
            "Sous traitance",
            "Maison arrêt BORDIOT",
            "HEAVY TAGS ",
            1000,
            "Il manque la pose du lastex sur de nombreuses étiquettes,\nLa série HEAVY TAGS : une boîte en vrac et sans cordons lastex\n",
            "Erreur opérateur",
            "Logistique",
            "ASP",
            44526,
            "C.LAUVERGEAT",
            "rappel et formalisation lors de la commande",
            44496,
            50,
            "OUI"
        ],
        [
            35,
            44509,
            44509,
            "NC Fournisseur",
            "Manter",
            "BL M21071288",
            undefined,
            "Palette abîmée",
            undefined,
            "Logistique",
            undefined,
            44539,
            undefined,
            undefined,
            44516,
            50,
            "OUI"
        ],
        [
            36,
            44519,
            44519,
            "NC Client",
            "POLE POSITION",
            "E042095",
            undefined,
            "étiquettes froissées en sortie d'impression chez le client",
            "l'opérateur n'a pas supprimé les étiquettes rouges et vertes",
            "Machine",
            "ASP",
            44549,
            "C.LAUVERGEAT",
            "sensiblisation",
            44519,
            50,
            "OUI"
        ],
        [
            37,
            44519,
            44519,
            "NC Fournisseur",
            "FERON",
            "BL 4102552",
            "10M²",
            "Etiquettes abîmés à réception (5 rouleaux défectueux sur 10)",
            "transporteur",
            "Logistique",
            undefined,
            44549,
            "N.LAVALETTE",
            "Information donnée",
            44519,
            50,
            "OUI"
        ],
        [
            38,
            44525,
            44525,
            "NC Fournisseur",
            "MANTER",
            "BL M21075596",
            "20m²",
            "Bobine abîmé à réception",
            undefined,
            "Logistique",
            "ASP",
            44555,
            "N.LAVALETTE",
            "transporteur (avoir reçu)",
            44544,
            50,
            "OUI"
        ],
        [
            39,
            44523,
            44523,
            "NC Client",
            "BARTHET",
            60441328,
            undefined,
            "2 colis éventrés/rouleaux abimés et pris l'eau",
            "Cause transporteur Schenker : \nLors du déchargement votre palette a était frotté par une autre palette qui était entrain d’être déchargé",
            "Logistique",
            "ASP",
            44553,
            "Audrey",
            "Schenker a sensibilisé ses chauffeurs et agents de quais pour faire attentions aux marchandises sur le quai lors de toutes manipulations\navoir au client/ remboursement",
            44533,
            130,
            "OUI"
        ],
        [
            40,
            44522,
            44522,
            "NC Interne",
            "Croquet charest",
            "E044510",
            undefined,
            "Manque d'étiquette BAT faux, mal repris sur le tableau\nErreur visuel sur Konica *2",
            "Erreur PAO des fichier sur Konika\nErreur PAO des reprises info sur BAT",
            "prépresse",
            "OPE",
            44552,
            "N.LAVALETTE",
            "Modification\nRefabrication",
            44523,
            250,
            "OUI"
        ],
        [
            41,
            44533,
            44533,
            "NC Client",
            "MONIN",
            "E044529\nE044528",
            240000,
            "Les étiquettes ne sont pas enroulés dans le bon sens et sont donc inutilisables en production",
            "• Habituellement c’est le bon sens d’enroulement chez nos principaux clients viticole\n• Opérateur n’a pas contrôlé le sens d’enroulement\n• Pas de Contrôle au conditionnement pour les clients spécifique (Monin)",
            "Machine",
            "ASP",
            44563,
            "C.LAUVERGEAT",
            "• Réunion de sensibilisation de tous le personnel le mardi 7 déc\n• Alerte qualité (voir annexe)\n• Contrôle planifié pour les clients spécifique (Monin) à chaque étape de production",
            44533,
            250,
            "OUI"
        ],
        [
            42,
            44533,
            44533,
            "NC Interne",
            "SOPREMA",
            "Cmde : 47/1",
            19000,
            "Impression noir : fichier non vérifié mis en quadri",
            "Erreur PAO pas mis le fichier en noir : oubli de l'opératrice",
            "prépresse",
            "ASP",
            44563,
            "N.LAVALETTE",
            "Tous kes fichiers en noir ne doivent pas contenir de quadri ",
            44533,
            800,
            "OUI"
        ],
        [
            43,
            44533,
            44533,
            "NC Client",
            "MONIN",
            "E044529\nE044528",
            undefined,
            "On retrouve des tâches blanches en plus ou moins grande quantité et plus ou moins visible dans l’inscription « Le Sirop de Monin »",
            "• Il s’agit de ce que nous appelons des « pétouille » occasionnés par des poussières, peluche qu’il y a dans l’air\n• La caméra de contrôle mentionnant les défauts à hauteur de 2,5 mm2. Il se peut que quelques petites poussières provoquent de tous petits manques",
            "Machine",
            "ASP",
            44563,
            "N.LAVALETTE",
            "• Passage durant le tirage d’un rouleau d’adhésif sur les clichés\n• Contrôle aléatoire sur un point donné par inspection BST\n",
            undefined,
            50,
            "PAS DE RETOUR DE MONIN"
        ],
        [
            44,
            44540,
            44540,
            "NC Client",
            "LP2I",
            "E044742",
            4000,
            "Les rouleaux ne sont pas serrés ni calés dans les cartons ==> Collés entre elles",
            "L'opératrice n'a pas calé les rouleaux comme prévu, Elle a fermé les cartons sans laisser à l'expédition la possibilité de caler les rouleaux et faire un dernier Check.",
            "Machine",
            "OPE",
            44570,
            "F.MUSE",
            "Sensibilisation et rappel des règles d'emballage.\nInstruction (bonne et mauvaise situation)\nPossibilité d'avoir au poste de l'opératrice des moyens de calage disponibles en cas de besoin.",
            44544,
            50,
            "OUI"
        ],
        [
            45,
            44544,
            44544,
            "NC Fournisseur",
            undefined,
            "Roll\n00384279731040772556",
            "120m²",
            "Erreur sur les dimensions bobine : \nCommandé 330mm*4000m=1320m²\nReçu : 300mm*4000m=1200m²\n\nIl manque 120m² en avoir",
            undefined,
            "Logistique",
            "DIM",
            44574,
            "N.LAVALETTE",
            undefined,
            undefined,
            50,
            undefined
        ],
        [
            46,
            44538,
            44538,
            "NC Interne",
            "Sel régional",
            undefined,
            undefined,
            "Cliché mauvais, 1 pose pas au même niveau que les autres",
            "Erreur de mise en page à la PAO",
            "prépresse",
            "OPE",
            44568,
            "F.MUSE",
            "Découpé le cliché par FM pour faire le tirage. Sur conso de matière",
            44538,
            300,
            "OUI"
        ],
        [
            47,
            44539,
            44539,
            "NC Interne",
            "Initial food",
            44735,
            undefined,
            "Mauvais cliché",
            "PAO cache trop fin",
            "prépresse",
            "OPE",
            44569,
            "PAO",
            "Refaire",
            44539,
            150,
            "OUI"
        ],
        [
            48,
            44547,
            44547,
            "NC Interne",
            "Girault",
            44668,
            undefined,
            "Erreur sérigraphie + cliché ==> Refus clients",
            "PAO calque de la sérigraphie aurait écrasé le filet noir",
            "prépresse",
            "OPE",
            44577,
            "PAO",
            "Plus de contrôle\nRefaire écran sérigraphie",
            44547,
            760,
            "OUI"
        ],
        [
            49,
            44550,
            44550,
            "NC Interne",
            "Jeff de Bruge",
            undefined,
            undefined,
            "erreur des sens de cliche PAO",
            "PAP",
            "prépresse",
            "OPE",
            44580,
            "PAO",
            "Plus de contrôle\nRefaire écran sérigraphie",
            44550,
            140,
            "OUI"
        ]
    
]

module.exports = data;